CREATE TABLE ProductSpecification (
  productNumber VARCHAR(5000) NOT NULL REFERENCES Product,
  name VARCHAR(200) NOT NULL,
  value VARCHAR(5000),
  PRIMARY KEY (productNumber, name)
);

ALTER TABLE Product ADD COLUMN category VARCHAR(100);

INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'audio', CAST(audio AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'color', CAST(color AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionDepthInInches', CAST(dimensionDepthInInches AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionHeightInInches', CAST(dimensionHeightInInches AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionWidthInInches', CAST(dimensionWidthInInches AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensions', CAST(dimensions AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyEfficiency', CAST(energyEfficiency AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'expansionSlots', CAST(expansionSlots AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'externalIOPorts', CAST(externalIOPorts AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'graphics', CAST(graphics AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'hardDrive', CAST(hardDrive AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'keyboard', CAST(keyboard AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memory', CAST(memory AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memorySlots', CAST(memorySlots AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'modelNumber', CAST(modelNumber AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'networking', CAST(networking AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'officeSoftware', CAST(officeSoftware AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingSystem', CAST(operatingSystem AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'opticalDrive', CAST(opticalDrive AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'photographySoftware', CAST(photographySoftware AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'pointingDevices', CAST(pointingDevices AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'popularSoftware', CAST(popularSoftware AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'ports', CAST(ports AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'powerSupply', CAST(powerSupply AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processor', CAST(processor AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'softwareIncluded', CAST(softwareIncluded AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'softwareUpgrades', CAST(softwareUpgrades AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'soundCard', CAST(soundCard AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'tvTurner', CAST(tvTurner AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'warranty', CAST(warranty AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weight', CAST(weight AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weightInPounds', CAST(weightInPounds AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'accessories', CAST(accessories AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'additionalApplicationSoftware', CAST(additionalApplicationSoftware AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'additionalNetworkingOptions', CAST(additionalNetworkingOptions AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'battery', CAST(battery AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'batteryLife', CAST(batteryLife AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'cableOptionKits', CAST(cableOptionKits AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'chassis', CAST(chassis AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'chinaCccCompliance', CAST(chinaCccCompliance AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'controller', CAST(controller AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'display', CAST(display AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'displayCable', CAST(displayCable AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyStar', CAST(energyStar AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'eightInternalStorage', CAST(eightInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'externalOpticalDrive', CAST(externalOpticalDrive AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'fempCompliance', CAST(fempCompliance AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'fifthInternalStorage', CAST(fifthInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'flashCache', CAST(flashCache AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'fourthInternalStorage', CAST(fourthInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'graphicsConnectors', CAST(graphicsConnectors AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'highPerformanceGpuComputing', CAST(highPerformanceGpuComputing AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'integratedCamera', CAST(integratedCamera AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'intelSrtDiskCacheModules', CAST(intelSrtDiskCacheModules AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'intelSmartResponseTechnology', CAST(intelSmartResponseTechnology AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'internalOsLoadStorageOptions', CAST(internalOsLoadStorageOptions AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'internalPcieStorage', CAST(internalPcieStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'internalStorageOptions', CAST(internalStorageOptions AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'lanTransceivers', CAST(lanTransceivers AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'label', CAST(label AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'maximumMemory', CAST(maximumMemory AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'securitySoftware', CAST(securitySoftware AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mediaReader', CAST(mediaReader AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memoryCardDevice', CAST(memoryCardDevice AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processorTechnology', CAST(processorTechnology AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'realTimeDataBackup', CAST(realTimeDataBackup AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'secondDisplayCable', CAST(secondDisplayCable AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'secondGraphicsCard', CAST(secondGraphicsCard AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'secondInternalStorage', CAST(secondInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'secondaryInternalPcieStorage', CAST(secondaryInternalPcieStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'secondaryOpticalDrive', CAST(secondaryOpticalDrive AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'secondaryProcessor', CAST(secondaryProcessor AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'security', CAST(security AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'securityEncryption', CAST(securityEncryption AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'sixthInternalStorage', CAST(sixthInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'seventhInternalStorage', CAST(seventhInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'softwareBundles', CAST(softwareBundles AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'speakers', CAST(speakers AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'stand', CAST(stand AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'systemRecoverySolutions', CAST(systemRecoverySolutions AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'tvTuner', CAST(tvTuner AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'technical', CAST(technical AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'technicalAV', CAST(technicalAV AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'thirdGraphicsCard', CAST(thirdGraphicsCard AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'thirdInternalStorage', CAST(thirdInternalStorage AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'webcam', CAST(webcam AS VARCHAR(5000)) FROM Desktop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'wireless', CAST(wireless AS VARCHAR(5000)) FROM Desktop;


INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'battery', CAST(battery AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'batteryLife', CAST(batteryLife AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'color', CAST(color AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionDepthInInches', CAST(dimensionDepthInInches AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionHeightInInches', CAST(dimensionHeightInInches AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionWidthInInches', CAST(dimensionWidthInInches AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensions', CAST(dimensions AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'display', CAST(display AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyEfficiency', CAST(energyEfficiency AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'expansionSlots', CAST(expansionSlots AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'graphics', CAST(graphics AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'hardDrive', CAST(hardDrive AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'keyboard', CAST(keyboard AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'maxBatteryLifeInHours', CAST(maxBatteryLifeInHours AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memory', CAST(memory AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'modelNumber', CAST(modelNumber AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'networking', CAST(networking AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingSystem', CAST(operatingSystem AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'pointingDevices', CAST(pointingDevices AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'ports', CAST(ports AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'powerSupply', CAST(powerSupply AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processor', CAST(processor AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'softwareIncluded', CAST(softwareIncluded AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'warranty', CAST(warranty AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'webcam', CAST(webcam AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weight', CAST(weight AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weightInPounds', CAST(weightInPounds AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'acAdapter', CAST(acAdapter AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'accessories', CAST(accessories AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'additionalBay', CAST(additionalBay AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'audio', CAST(audio AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'bluetooth', CAST(bluetooth AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'broadbandServiceProvider', CAST(broadbandServiceProvider AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'chipset', CAST(chipset AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'externalIOPorts', CAST(externalIOPorts AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'fingerPrintReader', CAST(fingerPrintReader AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'flashCache', CAST(flashCache AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'hpMobileBroadband', CAST(hpMobileBroadband AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'labelEnergyStar', CAST(labelEnergyStar AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'laplinkPcmoverSoftware', CAST(laplinkPcmoverSoftware AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'securitySoftware', CAST(securitySoftware AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memorySlots', CAST(memorySlots AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'miniCard', CAST(miniCard AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'miniCardSsd', CAST(miniCardSsd AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'miscWarrantyDocumentation', CAST(miscWarrantyDocumentation AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'modem', CAST(modem AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'nearFieldCommunication', CAST(nearFieldCommunication AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'osRecoveryCd', CAST(osRecoveryCd AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'officeSoftware', CAST(officeSoftware AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'opticalDrive', CAST(opticalDrive AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'outOfBandManagement', CAST(outOfBandManagement AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'personalization', CAST(personalization AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'powerCord', CAST(powerCord AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processorFamily', CAST(processorFamily AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processorTechnology', CAST(processorTechnology AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'recoveryMediaDriver', CAST(recoveryMediaDriver AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'securityManagement', CAST(securityManagement AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'sensors', CAST(sensors AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'theftProtection', CAST(theftProtection AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'warrantyBattery', CAST(warrantyBattery AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'boxContents', CAST(boxContents AS VARCHAR(5000)) FROM Laptop;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'wirelessLan', CAST(wirelessLan AS VARCHAR(5000)) FROM Laptop;



INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'automaticPaperSensor', CAST(automaticPaperSensor AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'borderlessPrinting', CAST(borderlessPrinting AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'cableIncluded', CAST(cableIncluded AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'compatibleInkTypes', CAST(compatibleInkTypes AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'compatibleOperatingSystems', CAST(compatibleOperatingSystems AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'connectivityOptional', CAST(connectivityOptional AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'connectivityStd', CAST(connectivityStd AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionDepthInInches', CAST(dimensionDepthInInches AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionDepthInInchesMax', CAST(dimensionDepthInInchesMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionHeightInInches', CAST(dimensionHeightInInches AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionHeightInInchesMax', CAST(dimensionHeightInInchesMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionWidthInInches', CAST(dimensionWidthInInches AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionWidthInInchesMax', CAST(dimensionWidthInInchesMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensions', CAST(dimensions AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionsMax', CAST(dimensionsMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'display', CAST(display AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'duplexPrinting', CAST(duplexPrinting AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyEfficiency', CAST(energyEfficiency AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'envelopeInputCapacity', CAST(envelopeInputCapacity AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'fcc', CAST(fcc AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'functions', CAST(functions AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'hardDisk', CAST(hardDisk AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mediaSizesCustom', CAST(mediaSizesCustom AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mediaSizesSupported', CAST(mediaSizesSupported AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mediaTypes', CAST(mediaTypes AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mediaWeightsByPaperPath', CAST(mediaWeightsByPaperPath AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memoryMax', CAST(memoryMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memoryStd', CAST(memoryStd AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'minimumSystemRequirements', CAST(minimumSystemRequirements AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mobilePrintingCapability', CAST(mobilePrintingCapability AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'networkReady', CAST(networkReady AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'numberPrintCartridges', CAST(numberPrintCartridges AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingHumidityRange', CAST(operatingHumidityRange AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingTemperatureRange', CAST(operatingTemperatureRange AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'packageWeight', CAST(packageWeight AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'packageWeightInPounds', CAST(packageWeightInPounds AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'paperHandlingInputStd', CAST(paperHandlingInputStd AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'paperHandlingOutputStd', CAST(paperHandlingOutputStd AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'paperTraysMax', CAST(paperTraysMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'paperTraysStd', CAST(paperTraysStd AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'postWarranty', CAST(postWarranty AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'power', CAST(power AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'powerConsumption', CAST(powerConsumption AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printerManagement', CAST(printerManagement AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printLanguages', CAST(printLanguages AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printSpeedBlackDraft', CAST(printSpeedBlackDraft AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printSpeedBlackISO', CAST(printSpeedBlackISO AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printSpeedColorDraft', CAST(printSpeedColorDraft AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printSpeedColorISO', CAST(printSpeedColorISO AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printTechnology', CAST(printTechnology AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printerPageYield', CAST(printerPageYield AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processorSpeed', CAST(processorSpeed AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'recommMonthlyPageVolume', CAST(recommMonthlyPageVolume AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'recommMonthlyPageVolumeMax', CAST(recommMonthlyPageVolumeMax AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'recommMonthlyPageVolumeMin', CAST(recommMonthlyPageVolumeMin AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'recommendedMediaWeight', CAST(recommendedMediaWeight AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'replacementCartridges', CAST(replacementCartridges AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'resolutionBlack', CAST(resolutionBlack AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'resolutionColor', CAST(resolutionColor AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'securityManagement', CAST(securityManagement AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'softwareIncluded', CAST(softwareIncluded AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'supportedMediaWeight', CAST(supportedMediaWeight AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'supportedNetworkProtocols', CAST(supportedNetworkProtocols AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'warranty', CAST(warranty AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weight', CAST(weight AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weightInPounds', CAST(weightInPounds AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'whatsInTheBox', CAST(whatsInTheBox AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'adfCapacity', CAST(adfCapacity AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'autoDocumentFeeder', CAST(autoDocumentFeeder AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'batteryRechargeTime', CAST(batteryRechargeTime AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'bitDepth', CAST(bitDepth AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'broadcastLocations', CAST(broadcastLocations AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'browserSupported', CAST(browserSupported AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'colorStability', CAST(colorStability AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'connectivity', CAST(connectivity AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'controlPanel', CAST(controlPanel AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'maximumCopies', CAST(maximumCopies AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copyReduceEnlargeSettings', CAST(copyReduceEnlargeSettings AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copyResolutionBlackText', CAST(copyResolutionBlackText AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copyResolutionColourTextGraphics', CAST(copyResolutionColourTextGraphics AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copySpeedBlackDraft', CAST(copySpeedBlackDraft AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copySpeedBlackNormal', CAST(copySpeedBlackNormal AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copySpeedColorDraft', CAST(copySpeedColorDraft AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'copySpeedColorNormal', CAST(copySpeedColorNormal AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'digitalSendFileFormats', CAST(digitalSendFileFormats AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'digitalSendingFeatures', CAST(digitalSendingFeatures AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'duplexAdfScanning', CAST(duplexAdfScanning AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyStar', CAST(energyStar AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'embeddedWebServer', CAST(embeddedWebServer AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'faxMemory', CAST(faxMemory AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'faxResolution', CAST(faxResolution AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'faxTransmissionSpeed', CAST(faxTransmissionSpeed AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'faxing', CAST(faxing AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'finishedOutputHandling', CAST(finishedOutputHandling AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'firstPageOutBlack', CAST(firstPageOutBlack AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'firstPageOutColor', CAST(firstPageOutColor AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'guaranteedMinimumLineWidth', CAST(guaranteedMinimumLineWidth AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'inputType', CAST(inputType AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'lineAccuracy', CAST(lineAccuracy AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'maximumDocumentScanSize', CAST(maximumDocumentScanSize AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'maximumOpticalDensityBlack', CAST(maximumOpticalDensityBlack AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptUsColorImageBestModeGlossy', CAST(mptUsColorImageBestModeGlossy AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptUsColorImageDraftModeCoated', CAST(mptUsColorImageDraftModeCoated AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptUsColorImageNormalModeCoated', CAST(mptUsColorImageNormalModeCoated AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptUsColorImageNormalModeGlossy', CAST(mptUsColorImageNormalModeGlossy AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptBWLineDrawingDraftModePlain', CAST(mptBWLineDrawingDraftModePlain AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptColorLineDrawingDraftModePlain', CAST(mptColorLineDrawingDraftModePlain AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mptLineDrawingEconomodePlain', CAST(mptLineDrawingEconomodePlain AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'mediaThickness', CAST(mediaThickness AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memoryCardCompatibility', CAST(memoryCardCompatibility AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'monthlyDutyCycle', CAST(monthlyDutyCycle AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'nonPrintableArea', CAST(nonPrintableArea AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'ports', CAST(ports AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printRepeatability', CAST(printRepeatability AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'printSpeedMaximum', CAST(printSpeedMaximum AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'resolution', CAST(resolution AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'resolutionTechnology', CAST(resolutionTechnology AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'rollExternalDiameter', CAST(rollExternalDiameter AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'rollMaximumOutput', CAST(rollMaximumOutput AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scanFileFormat', CAST(scanFileFormat AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scanResolutionHardware', CAST(scanResolutionHardware AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scanResolutionOptical', CAST(scanResolutionOptical AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scanSizeMaximum', CAST(scanSizeMaximum AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scanSizeFlatbedMaximum', CAST(scanSizeFlatbedMaximum AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scanSpeedMaximum', CAST(scanSpeedMaximum AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scannableMediaTypes', CAST(scannableMediaTypes AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'scannerType', CAST(scannerType AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'speedDialsMaximumNumber', CAST(speedDialsMaximumNumber AS VARCHAR(5000)) FROM Printer;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'usColorLineDrawingsDraftPlain', CAST(usColorLineDrawingsDraftPlain AS VARCHAR(5000)) FROM Printer;

INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'audio', CAST(audio AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'battery', CAST(battery AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'batteryLife', CAST(batteryLife AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'color', CAST(color AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionDepthInInches', CAST(dimensionDepthInInches AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionHeightInInches', CAST(dimensionHeightInInches AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensionWidthInInches', CAST(dimensionWidthInInches AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensions', CAST(dimensions AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'display', CAST(display AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'expansionSlots', CAST(expansionSlots AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'integratedCamera', CAST(integratedCamera AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'internalStorage', CAST(internalStorage AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'maxBatteryLifeInHours', CAST(maxBatteryLifeInHours AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'memory', CAST(memory AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'modelNumber', CAST(modelNumber AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingSystem', CAST(operatingSystem AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'ports', CAST(ports AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processor', CAST(processor AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'sensors', CAST(sensors AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'softwareIncluded', CAST(softwareIncluded AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'warranty', CAST(warranty AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weight', CAST(weight AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weightInPounds', CAST(weightInPounds AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'whatsInTheBox', CAST(whatsInTheBox AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'wireless', CAST(wireless AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'chipset', CAST(chipset AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyEfficiency', CAST(energyEfficiency AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'graphics', CAST(graphics AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'internalDrive', CAST(internalDrive AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'powerSupply', CAST(powerSupply AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processorFamily', CAST(processorFamily AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'processorTechnology', CAST(processorTechnology AS VARCHAR(5000)) FROM Tablet;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'securityManagement', CAST(securityManagement AS VARCHAR(5000)) FROM Tablet;

INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'nativeResolution', CAST(nativeResolution AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'contrastRatio', CAST(contrastRatio AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'brightness', CAST(brightness AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'pixelPitch', CAST(pixelPitch AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'responseTime', CAST(responseTime AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'displayTiltAndSwivelRange', CAST(displayTiltAndSwivelRange AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'energyEfficiency', CAST(energyEfficiency AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'dimensions', CAST(dimensions AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'weight', CAST(weight AS VARCHAR(5000)) FROM Monitor;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'whatsInTheBox', CAST(whatsInTheBox AS VARCHAR(5000)) FROM Monitor;


INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'colorsOfPrintCartridges', CAST(colorsOfPrintCartridges AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'pageYield', CAST(pageYield AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'pageYieldFootnote', CAST(pageYieldFootnote AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'inkDrop', CAST(inkDrop AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'compatibleInkTypes', CAST(compatibleInkTypes AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingTemperatureRange', CAST(operatingTemperatureRange AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'storageTemperatureRange', CAST(storageTemperatureRange AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'operatingHumidityRange', CAST(operatingHumidityRange AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'storageHumidity', CAST(storageHumidity AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'packageDimensions', CAST(packageDimensions AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'packageWeight', CAST(packageWeight AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'warranty', CAST(warranty AS VARCHAR(5000)) FROM InkAndToner;
INSERT INTO ProductSpecification (productNumber, name, value) SELECT productNumber, 'whatsInTheBox', CAST(whatsInTheBox AS VARCHAR(5000)) FROM InkAndToner;

COMMIT;

-- Use COMMIT, or the DB server will crash
UPDATE Product p SET category='Desktop' FROM Desktop s where s.productNumber = p.productNumber;
COMMIT;
UPDATE Product p SET category='Laptop' FROM Laptop s where s.productNumber = p.productNumber;
COMMIT;
UPDATE Product p SET category='Printer' FROM Printer s where s.productNumber = p.productNumber;
COMMIT;
UPDATE Product p SET category='Tablet' FROM Tablet s where s.productNumber = p.productNumber;
COMMIT;
UPDATE Product p SET category='Monitor' FROM Monitor s where s.productNumber = p.productNumber;
COMMIT;
UPDATE Product p SET category='InkAndToner' FROM InkAndToner s where s.productNumber = p.productNumber;
COMMIT;

--DROP TABLE Desktop;
--DROP TABLE Laptop;
--DROP TABLE Printer;
--DROP TABLE Tablet;
--DROP TABLE Monitor;
--DROP TABLE InkAndToner;
